### ISSUE TITLE
Product image not upload in S3 .

### ISSUE THREAD

**Issue by arunsalokhe** [thaiphan/magento2-s3#10]
I follow all steps of installation.And create one product with images but images still upload in local pub/media folder not on s3 bucket.

**Comment by thaiphan** [comment]
Hey @arunsalokhe,

Have you enabled S3 integration via the command line?

Regards,

Thai

**Comment by arunsalokhe** [comment]
Yes I enabled and also export is working but at time of create product
images not uploaded to s3 bucket

**Comment by thaiphan** [comment]
Is there any kind of error messages popping up?

**Comment by SmrtPeople** [comment]
Is this issue solved  or not ?

**Comment by SmrtPeople** [comment]
Hey @thaiphan ,

is this work with image upload from admin side ?

**Comment by satishgadhave** [comment]
Hi @thaiphan 
I'm facing same issue. My Magento version is 2.1.8

**Comment by rubenromao** [comment]
Hi @thaiphan
Same here.
I did all steps including the s3:storage:enable:
`rubenromao$ php -f bin/magento s3:storage:enable
Updating configuration to use S3.
Magento now uses S3 for its file backend storage.`
But all new images are still saved on filesystem not S3: `pub/media/catalog/product/r/u/rubenphoto2016.png`
My M2 version: 2.1.7
Thanks

**Comment by hassanazy** [comment]
i've the same issue in magento 2.1.7 , any help @thaiphan ?

**Comment by thaiphan** [comment]
Hi everyone,

@rubenromao 

If you are finding that you can upload to S3 but it's also saving to Magento then that is expected behaviour. Magento has a built-in caching mechanism where you download S3 files back onto the file system on load. It's totally safe to delete the file again from the file system **(always make sure to take backups just in case)**. If you want to stop Magento from downloading images onto the file system, you can try update the media URL via the admin panel to be S3 or CloudFront.

@SmrtPeople 

> is this work with image upload from admin side ?

Yes, it should be working. If you are having problems, can you clarify where you're having problems?

For everybody else, can you all create individual issues and explain more in detail what you have done so far and where you are stuck?

Regards,

**Comment by niranjan-gondaliya** [comment]
Hello @thaiphan ,

I am not able to upload to S3 Bucket when we upload image in Product from admin Panel.

**Comment by merin3** [comment]
@niranjan-gondaliya 
I'm also having the same problem , from admin panel one images gets upload other images shows static images of magento .

**Comment by niranjan-gondaliya** [comment]
> @niranjan-gondaliya
> I'm also having the same problem , from admin panel one images gets upload other images shows static images of magento .

Hello @merin3 ,

Now it working fine i am able to upload image to S3 Bucket from Product image, Category Image and WYSIWYG images.  Have you run php -f bin/magento s3:storage:enable command.

**Comment by merin3** [comment]
Yes i had already done it , And again done the same its telling 'You are already using S3 as your media file storage backend!' , Image download and upload issue is still persist.
